[workspace]
members = ["crates/*"]

[workspace.dependencies]
starknet = "2.7.0"
assert_macros = "2.8.2"
snforge_std = { path = "../../../snforge_std" }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
