[package]
name = "invoke"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
snforge_std.workspace = true
sncast_std.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
